# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IODC evening events
email: your-email@domain.com
description: "During IODC week we'll have a bunch of events
We want everyone to come and engage with the community!"

baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#sidebar
default-image: images/IODC16_logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Open Knowledge. Based on webjeda's theme

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

analytics:
disqus-shortname:

#social
facebook: http://facebook.com/opendatacon
twitter: http://twitter.com/opendatacon

sass:
  style: compressed

gems: [jekyll-paginate, jekyll-seo-tag]
